server.port: 9000
spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true

logging:
  level:
    org:
      springframework:
        security: TRACE
        oauth2: TRACE

# custom props
authserver:
  useradmin:
    username: admin
    password: admin
  registered-clients:
    inmemory-client:
      clientId: kek-admin-client
      clientSecret: MY SECRET
      redirectUri: http://localhost:3000/oauth2/callback
      scopes:
        - "first"
        - "second"
